apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: native
build:
  platforms: ["linux/amd64"]
  artifacts:
  - image: demo
    context: demo
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
  - image: eureka
    context: eureka
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
deploy:
  kubectl:
    manifests:
    - eureka/deployment.yaml
    - demo/deployment.yaml
